### ISSUE TITLE
global.json SDK version is 5.0.100, unsupported by Microsoft and Ionide

### ISSUE THREAD

**Issue by davedawkins** [fable-compiler/fable-browser#107]
This is low priority (for my own needs), but Chet Husk raises the point:

https://github.com/ionide/ionide-vscode-fsharp/issues/1813#issuecomment-1368117536

Mainly I'm interested how we decide what SDK is best for widely-used projects like this one - is it safe to jump right up to `7.*` or should be pick the latest `6.*` (despite MS's recommendations), or leave it at `5.*` in case we break anything?

**Comment by MangelMaxime** [comment]
I think using LTS is best probably.

For compiling DLL I guess that doesn't matter too much which SDK we use as long we don't change the target. However for project which are libraries and need Fable to compile the demo, sample `7.*` is not safe because Fable 3 doesn't handle it correctly...

https://github.com/fable-compiler/Fable/issues/3294

**Comment by davedawkins** [comment]
Thank you. [LTS is 6.0](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core), and in the linked issue you recommend 
```json
{
    "sdk": {
        "version": "6.0.0",
        "rollForward": "latestMinor"
    }
}
```
I'll make a PR for this

**Comment by MangelMaxime** [comment]
Thank you

**Comment by davedawkins** [comment]
Sorry that I missed the edit needed for the YML

**Comment by MangelMaxime** [comment]
No problem
