### ISSUE TITLE
window.Navigator is missing

### ISSUE THREAD

**Issue by 0x53A** [fable-compiler/fable-browser#15]
https://developer.mozilla.org/en-US/docs/Web/API/Window/navigator

**Comment by alfonsogarciacaro** [comment]
Yes, it doesn't belong to the DOM API so probably we need a new package for it.

**Comment by aparent-emgs** [comment]
Hi! The package is still in beta and the issue is still opened. Is it safe to use this already? Why is it still this way since last June?

**Comment by MangelMaxime** [comment]
Yes, it's safe to use it, it's in beta because we didn't take the time to take it out of beta. But it's being used in production since day 1 :)

The package `Fable.Browser.Navigator` exist so I guess this issue is actually solved. You can use the Navigator API by adding `Fable.Browser.Navigator` to your project.
