### ISSUE TITLE
Add ScrollToOptions Support

### ISSUE THREAD

**Issue by saboco** [fable-compiler/fable-browser#63]
Would you accept a PR to add [ScrollToOptions ](https://developer.mozilla.org/en-US/docs/Web/API/ScrollToOptions) support for window here:

https://github.com/fable-compiler/fable-browser/blob/5ff9e588d7b21806eabb51aed511ddafe69c0247/src/Dom/Browser.Dom.fs#L972

Something like:

```fsharp
[<StringEnum>]
type ScrollBehaviour =
    | Auto
    | Smooth

type ScrollToOptions =
    { top : float
      left : float
      behavior: ScrollBehaviour }

type Window =
    (*old code as before *)
    ...
    abstract scroll: ?x: float * ?y: float -> unit
    abstract scrollBy: ?x: float * ?y: float -> unit
    abstract scrollTo: ?x: float * ?y: float -> unit
    (* new code *)
    abstract scroll : ScrollToOptions -> unit
    abstract scrollBy : ScrollToOptions -> unit
    abstract scrollTo : ScrollToOptions -> unit
```

**Comment by alfonsogarciacaro** [comment]
That'd be very helpful @saboco, thank you! Please do send the PR and I'll merge and push a new release :+1: According to MDN, `Element` also accepts scroll/By/To so it may be a good opportunity to also add the methods and the overloads to the Element type: https://github.com/fable-compiler/fable-browser/blob/5ff9e588d7b21806eabb51aed511ddafe69c0247/src/Dom/Browser.Dom.fs#L425

Also, maybe you can use an anonymous records so Fable compiles the options as a POJO instead of a class:

```fsharp
type ScrollToOptions =
    {| top : float
       left : float
       behavior: ScrollBehaviour |}
```
